{
 "title": "New dashboard",
 "time": { "from": "2020-12-14T20:00:00.000Z", "to": "2020-12-14T22:59:59.000Z" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='system'}[5m])) * 100"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user'}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(project_app_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Memory usage (mode=idle)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes- (node_memory_Cached_bytes+ node_memory_Buffers_bytes+ node_memory_MemFree_bytes)",
     "legendFormat": "In use"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "MemFree" }
   ]
  },
  {
   "title": "Percentage of exceptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(project_app_exception_total[1m])/rate(project_app_requests_total[1m])"
    }
   ]
  },
  {
   "title": "process_virtual_memory",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"Project App\"}"
    }
   ]
  },
  {
   "title": "Percentage of latency histogram bucket(le=0.1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "project_app_latency_histogram_seconds_bucket{le=\"0.1\"} / ignoring(le)project_app_latency_histogram_seconds_bucket{le=\"+Inf\"}"
    }
   ]
  },
  {
   "title": "project_app_latency_histogram_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "project_app_latency_histogram_seconds_bucket{le=\"0.1\"}",
     "legendFormat": "le = 0.1"
    },
    {
     "expr": "project_app_latency_histogram_seconds_bucket{le=\"1.0\"}",
     "legendFormat": "le = 1.0"
    }
   ]
  }
 ]
}